name: Release Python

on:
  release:
    types:
      - prereleased
      - released

permissions:
  contents: read
  id-token: write
  packages: write
  pull-requests: write

jobs:
  python-release:
    name: Release Python Application
    uses: srekit/github-workflows/.github/workflows/release-python.yaml@feature/release-python
    with:
      image-tag: ${{ github.event.release.tag_name }}
